const countries = [
  {
    id: 1,
    name: "Uzbekistan",
    capital: "Tashkent",
    population: 36000000,
    flag: "https://flagcdn.com/w320/uz.png",
    liked: false,
    saved: false,
  },
  {
    id: 2,
    name: "Japan",
    capital: "Tokyo",
    population: 125000000,
    flag: "https://flagcdn.com/w320/jp.png",
    liked: false,
    saved: false,
  },
  {
    id: 3,
    name: "Germany",
    capital: "Berlin",
    population: 83000000,
    flag: "https://flagcdn.com/w320/de.png",
    liked: false,
    saved: false,
  },
  {
    id: 4,
    name: "France",
    capital: "Paris",
    population: 67000000,
    flag: "https://flagcdn.com/w320/fr.png",
    liked: false,
    saved: false,
  },
  {
    id: 5,
    name: "United States",
    capital: "Washington, D.C.",
    population: 331000000,
    flag: "https://flagcdn.com/w320/us.png",
    liked: false,
    saved: false,
  },
  {
    id: 6,
    name: "United Kingdom",
    capital: "London",
    population: 68000000,
    flag: "https://flagcdn.com/w320/gb.png",
    liked: false,
    saved: false,
  },
  {
    id: 7,
    name: "Canada",
    capital: "Ottawa",
    population: 38000000,
    flag: "https://flagcdn.com/w320/ca.png",
    liked: false,
    saved: false,
  },
  {
    id: 8,
    name: "China",
    capital: "Beijing",
    population: 1410000000,
    flag: "https://flagcdn.com/w320/cn.png",
    liked: false,
    saved: false,
  },
  {
    id: 9,
    name: "South Korea",
    capital: "Seoul",
    population: 52000000,
    flag: "https://flagcdn.com/w320/kr.png",
    liked: false,
    saved: false,
  },
  {
    id: 10,
    name: "Italy",
    capital: "Rome",
    population: 59000000,
    flag: "https://flagcdn.com/w320/it.png",
    liked: false,
    saved: false,
  },
  {
    id: 11,
    name: "Spain",
    capital: "Madrid",
    population: 47000000,
    flag: "https://flagcdn.com/w320/es.png",
    liked: false,
    saved: false,
  },
  {
    id: 12,
    name: "Brazil",
    capital: "Brasília",
    population: 213000000,
    flag: "https://flagcdn.com/w320/br.png",
    liked: false,
    saved: false,
  },
  {
    id: 13,
    name: "Argentina",
    capital: "Buenos Aires",
    population: 45000000,
    flag: "https://flagcdn.com/w320/ar.png",
    liked: false,
    saved: false,
  },
  {
    id: 14,
    name: "Mexico",
    capital: "Mexico City",
    population: 126000000,
    flag: "https://flagcdn.com/w320/mx.png",
    liked: false,
    saved: false,
  },
  {
    id: 15,
    name: "India",
    capital: "New Delhi",
    population: 1400000000,
    flag: "https://flagcdn.com/w320/in.png",
    liked: false,
    saved: false,
  },
  {
    id: 16,
    name: "Australia",
    capital: "Canberra",
    population: 26000000,
    flag: "https://flagcdn.com/w320/au.png",
    liked: false,
    saved: false,
  },
  {
    id: 17,
    name: "New Zealand",
    capital: "Wellington",
    population: 5100000,
    flag: "https://flagcdn.com/w320/nz.png",
    liked: false,
    saved: false,
  },
  {
    id: 18,
    name: "Turkey",
    capital: "Ankara",
    population: 85000000,
    flag: "https://flagcdn.com/w320/tr.png",
    liked: false,
    saved: false,
  },
  {
    id: 19,
    name: "Saudi Arabia",
    capital: "Riyadh",
    population: 36000000,
    flag: "https://flagcdn.com/w320/sa.png",
    liked: false,
    saved: false,
  },
  {
    id: 20,
    name: "Indonesia",
    capital: "Jakarta",
    population: 275000000,
    flag: "https://flagcdn.com/w320/id.png",
    liked: false,
    saved: false,
  }
]